name: mc-IPGuard
version: '2.0.0'
main: hu.kxtsoo.ipguard.IPGuard
api-version: '1.20'
author: "kxtsoo"
folia-supported: true

softdepend: [AuthMe, nLogin]

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214
  - com.squareup.okhttp3:okhttp:4.10.0