name: gIPGuard
version: '1.0.4'
main: hu.kitsoo.gipguard.GIPGuard
tab-completer: hu.kitsoo.gipguard.util.TabCompleter
api-version: '1.16'
author: "kitsoo_"
softdepend: [AuthMe, nLogin]

commands:
  gipguard:
    description: 'List the command arguments'
    aliases: ["gig", "ipguard"]
    subcommands:
      reload:
        description: 'Reload the plugin files.'
        usage: '/gipguard reload'
      add:
        description: 'Assign an IP Address to an account.'
        usage: '/gipguard add <player> <ip>'
      remove:
        description: 'Delete the players details from the database.'
        usage: '/gipguard remove <player>'
      list:
        usage: '/gipguard list'
      check:
        usage: '/gipguard check <player>'
      activate:
        usage: '/gipguard activate'